// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DeployCommand
{
    internal sealed partial class Vsix
    {
        public const string Id = "DeployCommand.35bc9522-2fcf-4641-a362-5a1063deea85";
        public const string Name = "DeployCommand";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "ROHAN SHARMA";
        public const string Tags = "";
    }
}
